const servers = [
  'Anathema',
  'Arcanite Reaper',
  'Arugal',
  'Ashkandi',
  'Atiesh',
  'Azuresong',
  'Benediction',
  'Bigglesworth',
  'Blaumeux',
  'Bloodsail Buccaneers',
  'Deviate Delight',
  'Earthfury',
  'Faerlina',
  'Fairbanks',
  'Felstriker',
  'Grobbulus',
  'Heartseeker',
  'Herod',
  'Incendius',
  'Kirtonos',
  'Kromcrush',
  'Kurinnaxx',
  'Loatheb',
  'Mankrik',
  'Myzrael',
  'Netherwind',
  'Old Blanchy',
  'Pagle',
  'Rattlegore',
  'Remulos',
  'Skeram',
  'Smolderweb',
  'Stalagg',
  "Sul'thraze",
  'Sulfuras',
  'Thalnos',
  'Thunderfury',
  'Westfall',
  'Whitemane',
  'Windseeker',
  'Yojamba'
]

export default servers 